QT.mqtt.VERSION = 5.15.3
QT.mqtt.name = QtMqtt
QT.mqtt.module = Qt5Mqtt
QT.mqtt.libs = $$QT_MODULE_LIB_BASE
QT.mqtt.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/QtMqtt
QT.mqtt.frameworks =
QT.mqtt.bins = $$QT_MODULE_BIN_BASE
QT.mqtt.depends = core network
QT.mqtt.uses =
QT.mqtt.module_config = v2
QT.mqtt.DEFINES = QT_MQTT_LIB
QT.mqtt.enabled_features =
QT.mqtt.disabled_features =
QT_CONFIG +=
QT_MODULES += mqtt
